services:
  nginx:
    build: config/nginx
    restart: unless-stopped
    depends_on:
     - db
    volumes:
      - wp_data:/var/www/html:ro
    ports:
      - "4443:443"
  db:
    build: config/db
    restart: unless-stopped
    volumes: 
      - "${MARIADB_DATA_DIR}:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  wordpress:
    build: config/wordpress
    restart: unless-stopped
    depends_on:
      - db
      - nginx
    volumes:
      - wp_data:/var/www/html

networks:
  lan:
    driver: bridge

volumes:
  wp_data:
