services:
  nginx:
    build: config/nginx
    restart: unless-stopped
    depends_on:
     - db
    volumes:
      - wp_data:/var/www/html:ro
    ports:
      - "443:443"
  db:
    build: config/db
    restart: unless-stopped
    volumes: 
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
    - '3306:3306'
  wordpress:
    build: config/wordpress
    restart: unless-stopped
    depends_on:
      - db
      - nginx
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      WP_URL: "${WP_URL}"
      WP_TITLE: "${WP_TITLE}"
      WP_ADMIN_USER: "${WP_ADMIN_USER}"
      WP_ADMIN_PASSWORD: "${WP_ADMIN_PASSWORD}"
      WP_ADMIN_EMAIL: "${WP_ADMIN_EMAIL}"
      WP_USER: "${WP_USER}"
      WP_USER_PASSWORD: "${WP_USER_PASSWORD}"
      WP_USER_EMAIL: "${WP_USER_EMAIL}"
      WP_DEBUG: "${WP_DEBUG}"
      WP_DEBUG_LOG: "${WP_DEBUG_LOG}"
      WP_DEBUG_DISPLAY: "${WP_DEBUG_DISPLAY}"
    volumes:
      - wp_data:/var/www/html
  adminer:
    build: config/adminer
    restart: unless-stopped
    depends_on:
      - db
  gateau:
    build: config/gateau
    restart: unless-stopped

networks:
  lan:
    driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tstephan/data/wordpress
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tstephan/data/mariadb
